---
- name: Create mongodb group
  group:
    name: "{{ mongodb_system_group }}"
    state: present
    system: true

- name: create mongodb user
  user:
    name: "{{ mongodb_system_user }}"
    group: "{{ mongodb_system_group }}"
    system: true
    create_home: false
    state: present

# Workaround because default(omit) is not working. At least in Ansible 2.8.

- name: Create log dir if missing
  file:
    state: directory
    recurse: true
    dest: "{{ mongodb_systemlog_path|dirname }}"
    owner: "{{ mongodb_system_user }}"
    group: "{{ mongodb_system_group }}"
    mode: 0755
  when: mongodb_systemlog_destination == "file"

- name: Check that logfile exists
  stat:
    path: "{{ mongodb_systemlog_path }}"
  register: logfile_stat
  when: mongodb_systemlog_destination == "file"

- name: Create log if missing
  file:
    state: touch
    dest: "{{ mongodb_systemlog_path }}"
    owner: "{{ mongodb_system_user }}"
    group: "{{ mongodb_system_group }}"
    mode: 0755
  when: ( mongodb_systemlog_destination == "file"
        and logfile_stat is defined
        and not logfile_stat.stat.exists )

- name: Configure mongodb
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    backup: true
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart mongodb
    - Service started
    - Wait for mongodb to start

- name: Flush all handlers
  meta: flush_handlers
