---
- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install requirements for pymongo
  package:
    name: ["python-pip", "python-setuptools", "ca-certificates"]
    state: present
  when: mongodb_use_pymongo

- name: Install pymongo
  pip:
    name: pymongo
    state: present
  when: mongodb_use_pymongo

- include_tasks: "setup-{{ ansible_os_family }}.yml"

- include_tasks: "configure.yml"
