---
- name: Add APT key for MongoDB
  apt_key:
    url: "{{ mongodb_apt_keyserver }}"
    state: present

- name: Add APT repository for MongoDB
  apt_repository:
    repo: "{{ mongodb_apt_repository }}"
    filename: mongodb_rep
    state: present
    update_cache: true

- name: Installation de Mongodb
  package:
    name: "{{ mongodb_package_name }}"
    state: present

- name: Hold MongoDB version (Debian)
  dpkg_selections:
    name: "{{ mongodb_package_name }}"
    selection: "hold"
  when: mongodb_version_lock

- name: Add systemd configuration if present
  copy:
    src: mongodb.service 
    dest: "/lib/systemd/system/{{ mongodb_daemon_name }}.service"
    owner: root
    group: root
    mode: "0644"
  when: ansible_service_mgr == "systemd"
  notify: Reload systemd

- name: Add symlink for systemd
  file:
    src: "/lib/systemd/system/{{ mongodb_daemon_name }}.service"
    dest: "/etc/systemd/system/multi-user.target.wants/{{ mongodb_daemon_name }}.service"
    state: link
  when: ansible_service_mgr == "systemd"
  notify: Reload systemd

- name: Enable mongodb service on boot
  service:
    name: "{{ mongodb_daemon_name }}"
    state: started
    enabled: true
