---
- name: Establish some role-related facts
  set_fact:
    mongodb_major_version: "{{ mongodb_version[0:3] }}"

- name: Add APT key for MongoDB
  apt_key:
    keyserver: "{{ mongodb_apt_keyserver }}"
    id: "{{ mongodb_apt_key_id[mongodb_major_version] }}"
  when: mongodb_package == 'mongodb-org'

- name: Add APT repository for MongoDB
  apt_repository:
    repo: "{{ mongodb_repository[mongodb_major_version] }}"
    filename: mongodb_rep
    state: present
    update_cache: true

- name: Installation de Mongodb
  package:
    name: "{{ mongodb_package }}"
    state: present
    update_cache: true

- name: Install numactl package
  package:
    name: numactl
    state: present

- name: Hold MongoDB version (Debian)
  dpkg_selections:
    name: "{{ mongodb_package }}"
    selection: "hold"
  when: mongodb_version_lock

- name: Copy Mongodb init script into place.
  template:
    src: mongodb.init.j2
    dest: "/etc/init.d/{{ mongodb_daemon_name }}"
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr != 'systemd'"

- name: Add systemd configuration if present
  template:
    src: mongodb.service.j2
    dest: "/lib/systemd/system/{{ mongodb_daemon_name }}.service"
    owner: root
    group: root
    mode: "0644"
  when: "ansible_service_mgr == 'systemd'"
  notify: Reload systemd

- name: Add symlink for systemd
  file:
    src: "/lib/systemd/system/{{ mongodb_daemon_name }}.service"
    dest: "/etc/systemd/system/multi-user.target.wants/{{ mongodb_daemon_name }}.service"
    state: link
  when: "ansible_service_mgr == 'systemd'"
  notify: Reload systemd
