---
- name: Install Requisites
  package:
    name: ["python3-pip", "ca-certificates", "python3-setuptools"]
    state: present
    update_cache: true

- name: Install PyMongo from PIP
  pip:
    name: pymongo
    state: "present"

- name: Add APT key
  apt_key:
    url: "{{ mongodb_apt_keyserver }}"
    state: present

- name: Add APT repository for MongoDB
  apt_repository:
    repo: "{{ mongodb_repository }}"
    filename: mongodb_rep
    state: present

- name: Update apt cache.
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install MongoDB package
  package:
    name: "{{ mongodb_package }}{% if (mongodb_version | length > 3) %}={{ mongodb_version }}{% endif %}"
    state: present
    update_cache: true

- name: Install numactl package
  package:
    name: numactl
    state: present

- name: Hold MongoDB version (Debian)
  dpkg_selections:
    name: "{{ mongodb_package }}"
    selection: "hold"
  when: mongodb_version_lock

- name: Add systemd configuration if present
  copy:
    src: "mongodb.service"
    dest: "/lib/systemd/system/{{ mongodb_daemon_name }}.service"
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == "systemd"
  notify: Reload systemd

- name: Add symlink for systemd
  file:
    src: /lib/systemd/system/{{ mongodb_daemon_name }}.service
    dest: /etc/systemd/system/multi-user.target.wants/{{ mongodb_daemon_name }}.service
    state: link
  when: ansible_service_mgr == "systemd"
  notify: Reload systemd

- name: Flush handlers
  meta: flush_handlers
