---
- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart MongoDB
  service:
    name: "{{ mongodb_daemon_name }}"
    state: restarted

- name: Service started
  service:
    name: "{{ mongodb_daemon_name }}"
    state: started
    enabled: true

- name: Wait for mongodb to start
  wait_for:
    host: "{{ item }}"
    port: "{{ mongodb_net_port }}"
    timeout: 120
  with_items: "{{ mongodb_net_bindip.split(',') | map('replace', '0.0.0.0', '127.0.0.1') | list }}"
