---
- name: Reload systemd
  systemd:
    daemon_reload: true
  notify: Service started

- name: Restart mongodb
  service:
    name: "{{ mongodb_daemon_name }}"
    state: restarted

- name: Service started
  service:
    name: "{{ mongodb_daemon_name }}"
    state: started
    enabled: true
