---
- name: Converge
  hosts: all
  roles:
    - role: supertarto.mongodb

  vars:
    mongodb_user_update_password: "on_create"
    mongo_admin_roles: userAdminAnyDatabase
    mongo_admin_pass: "ChangeIT!"
    mongo_admin_user: admin
    mongodb_security_authorization: 'enabled'

    mongodb_users:
      - name: "user1"
        database: "database1"
        password: "ChangeIT!"
        roles:
          - readWrite
